// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.1
// source: user_media_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface GetUserMediaListRequest {
  userId: string;
}

export interface GetUserMediaListResponse {
  mediaList: Media[];
}

export interface AddMediaToUserRequest {
  userId: string;
  mediaId: string;
  mediaType: string;
}

export interface AddMediaToUserResponse {
  success: boolean;
  message?: string | undefined;
}

export interface Media {
  mediaId: string;
  mediaType: string;
  seen: boolean;
}

export const USER_PACKAGE_NAME = "user";

export interface UserMediaServiceClient {
  getUserMediaList(request: GetUserMediaListRequest): Observable<GetUserMediaListResponse>;

  addMediaToUser(request: AddMediaToUserRequest): Observable<AddMediaToUserResponse>;
}

export interface UserMediaServiceController {
  getUserMediaList(
    request: GetUserMediaListRequest,
  ): Promise<GetUserMediaListResponse> | Observable<GetUserMediaListResponse> | GetUserMediaListResponse;

  addMediaToUser(
    request: AddMediaToUserRequest,
  ): Promise<AddMediaToUserResponse> | Observable<AddMediaToUserResponse> | AddMediaToUserResponse;
}

export function UserMediaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUserMediaList", "addMediaToUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserMediaService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserMediaService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_MEDIA_SERVICE_NAME = "UserMediaService";
